### ISSUE TITLE
fullname

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloworld_c#1]
aggiusta il gitignore

**Comment by FabioZTessitore** [comment]
ricordati di caricare

**Comment by Edivad1234** [comment]
Prof. buonasera, ora sono a Vairano per l'allenamento appena torno, carico!

**Comment by FabioZTessitore** [comment]
figurati, buon divertimento

**Comment by Edivad1234** [comment]
Prof. buonasera! Ho caricato il programma figure.c, non riesco a capire
perchè nella compilazione mi da "Fatal error: stdio.h; No such file or
directory". Sapete dirmi il perchè?

2017-02-11 17:45 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
fai uno screenshot del terminale (in cui sia visibile il comando di compilazione)

**Comment by Edivad1234** [comment]
Prof. ho caricato "figure.c"

2017-02-13 17:34 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Ok

**Comment by Edivad1234** [comment]
Buonasera, ho caricato il programma "operazioni.c", dovrebbe funzionare!

2017-02-16 20:11 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:
