### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloworld_c#3]
in attesa

**Comment by Edivad1234** [comment]
Ho caricato anche "cerchio.c", dovrebbe funzionare anche questo!

2017-02-22 22:31 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
se funziona, funziona male. Controlla s e c

**Comment by Edivad1234** [comment]
Buonasera, ho caricato maggiore2.c e maggiore5.c, però non riesco a capire
come si fa il "somma_cifre.c"!

2017-02-24 9:16 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:
