### ISSUE TITLE
maggiore tra 2

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloworld_c#4]
prova a rifarlo usando un solo if (senza else if, senza else)

**Comment by Edivad1234** [comment]
Prof. finalmente ho caricato somma_cifre.c, dovrebbe funzionare! Però non
riesco a fare maggiore2.c senza usare else if ed else!

2017-03-01 15:40 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Hehe spremi il cervello

**Comment by FabioZTessitore** [comment]
niente?

**Comment by FabioZTessitore** [comment]
aggiusta

**Comment by FabioZTessitore** [comment]
carica la versione giusta

**Comment by Edivad1234** [comment]
Prof. buonasera, finalmente sono riuscito a caricare "maggiore2.c"!

2017-03-29 18:38 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Edivad1234** [comment]
Posso  proseguire?

2017-04-03 19:52 GMT+02:00 Davide Antonucci <davide.antonucci5@gmail.com>:
